name: Verible linter
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@main
    - uses: chipsalliance/verible-linter-action@main
      with:
        paths: |
          ./rtl
        extra_args: "--check_syntax=true"
        extensions: |
          .sv
          .v
          .vh
          .svh
        github_token: ${{ secrets.GITHUB_TOKEN }}
